### ISSUE TITLE
Crash while scanning after update version 4.1.0 to 4.4.0

### ISSUE THREAD

**Issue by loaloel** [BlinkID/blinkid-android#136]
Hi. I'm getting crash after updating version to 4.4.0. on version 4.1.0 scan was fine. but on 4.4.0 scan crash and write this log. 

Please help me with this issue.

> 2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64: Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.support.v4.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, android.support.v4.view.OnApplyWindowInsetsListener) (ViewCompat.java:2203)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at android.view.ViewGroup android.support.v7.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:637)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.support.v7.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:466)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.support.v7.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void com.pede.emoney.ui.activity.account.pedePlus.scanKTP.UploadIDCardActivity.onCreate(android.os.Bundle) (UploadIDCardActivity.java:208)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7148)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7139)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1220)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2913)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:3038)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1739)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.os.Looper.loop() (Looper.java:192)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6801)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:825)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.pede.emoney-CJ6LJ6DIEtcsbnhEcOU8Sw==/base.apk"],nativeLibraryDirectories=[/data/app/com.pede.emoney-CJ6LJ6DIEtcsbnhEcOU8Sw==/lib/arm64, /data/app/com.pede.emoney-CJ6LJ6DIEtcsbnhEcOU8Sw==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.support.v4.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, android.support.v4.view.OnApplyWindowInsetsListener) (ViewCompat.java:2203)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at android.view.ViewGroup android.support.v7.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:637)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.support.v7.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:466)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.support.v7.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void com.pede.emoney.ui.activity.account.pedePlus.scanKTP.UploadIDCardActivity.onCreate(android.os.Bundle) (UploadIDCardActivity.java:208)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7148)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7139)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1220)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2913)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:3038)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1739)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.os.Looper.loop() (Looper.java:192)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6801)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:825)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64: Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.support.v4.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, android.support.v4.view.OnApplyWindowInsetsListener) (ViewCompat.java:2203)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at android.view.ViewGroup android.support.v7.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:637)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.support.v7.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:466)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.support.v7.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void com.pede.emoney.ui.activity.account.pedePlus.scanKTP.UploadIDCardActivity.onCreate(android.os.Bundle) (UploadIDCardActivity.java:208)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7148)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7139)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1220)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2913)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:3038)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1739)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.os.Looper.loop() (Looper.java:192)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6801)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:825)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.pede.emoney-CJ6LJ6DIEtcsbnhEcOU8Sw==/base.apk"],nativeLibraryDirectories=[/data/app/com.pede.emoney-CJ6LJ6DIEtcsbnhEcOU8Sw==/lib/arm64, /data/app/com.pede.emoney-CJ6LJ6DIEtcsbnhEcOU8Sw==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.support.v4.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, android.support.v4.view.OnApplyWindowInsetsListener) (ViewCompat.java:2203)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at android.view.ViewGroup android.support.v7.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:637)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.support.v7.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:466)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.support.v7.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void com.pede.emoney.ui.activity.account.pedePlus.scanKTP.UploadIDCardActivity.onCreate(android.os.Bundle) (UploadIDCardActivity.java:208)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7148)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7139)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1220)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2913)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:3038)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1739)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.os.Looper.loop() (Looper.java:192)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6801)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
2018-11-23 11:21:47.315 25051-25051/com.pede.emoney I/zygote64:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:825)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64: Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void android.support.v4.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, android.support.v4.view.OnApplyWindowInsetsListener) (ViewCompat.java:2203)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at android.view.ViewGroup android.support.v7.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:637)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void android.support.v7.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:466)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void android.support.v7.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void com.pede.emoney.ui.activity.account.pedePlus.scanKTP.UploadIDCardActivity.onCreate(android.os.Bundle) (UploadIDCardActivity.java:208)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7148)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7139)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1220)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2913)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:3038)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1739)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void android.os.Looper.loop() (Looper.java:192)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6801)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:825)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.pede.emoney-CJ6LJ6DIEtcsbnhEcOU8Sw==/base.apk"],nativeLibraryDirectories=[/data/app/com.pede.emoney-CJ6LJ6DIEtcsbnhEcOU8Sw==/lib/arm64, /data/app/com.pede.emoney-CJ6LJ6DIEtcsbnhEcOU8Sw==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void android.support.v4.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, android.support.v4.view.OnApplyWindowInsetsListener) (ViewCompat.java:2203)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at android.view.ViewGroup android.support.v7.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:637)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void android.support.v7.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:466)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void android.support.v7.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void com.pede.emoney.ui.activity.account.pedePlus.scanKTP.UploadIDCardActivity.onCreate(android.os.Bundle) (UploadIDCardActivity.java:208)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7148)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7139)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1220)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2913)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:3038)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1739)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void android.os.Looper.loop() (Looper.java:192)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6801)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
2018-11-23 11:21:47.316 25051-25051/com.pede.emoney I/zygote64:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:825)

**Comment by i1E** [comment]
Hi @loaloel,

from the given log we didn't find that this crash is related to our SDK, things from our SDK are not mentioned. One thing that may cause similar problems is that our SDK v4.4.0 transitively depends on latest com.android.support:appcompat-v7:28.0.0, and dependency for BlinkID v4.1.0 was com.android.support:appcompat-v7:27.1.1. In your application all com.android.support libraries must use the exact same version (mixing versions can lead to runtime crashes).

**Comment by ArmanIzad** [comment]
> Hi @loaloel,
> 
> from the given log we didn't find that this crash is related to our SDK, things from our SDK are not mentioned. One thing that may cause similar problems is that our SDK v4.4.0 transitively depends on latest com.android.support:appcompat-v7:28.0.0, and dependency for BlinkID v4.1.0 was com.android.support:appcompat-v7:27.1.1. In your application all com.android.support libraries must use the exact same version (mixing versions can lead to runtime crashes).

Sorry for hijacking, but saw your response and now I have some concerns because we're using androidx.appcompat namespace instead of the old android.support.appcompat. Would this cause any issues?

**Comment by i1E** [comment]
Hi @ArmanIzad, 

This should work without any problems, just follow official ["Migrating to AndroidX"](https://developer.android.com/jetpack/androidx/migrate) instructions.

> If you have any Maven dependencies that have not been migrated to the AndroidX namespace, the Android Studio build system also migrates those dependencies for you when you set the following two flags to true in your gradle.properties file:

```
android.useAndroidX=true
android.enableJetifier=true
```

In case of any problems, please contact us.

**Comment by ArmanIzad** [comment]
> Hi @ArmanIzad,
> 
> This should work without any problems, just follow official ["Migrating to AndroidX"](https://developer.android.com/jetpack/androidx/migrate) instructions.
> 
> > If you have any Maven dependencies that have not been migrated to the AndroidX namespace, the Android Studio build system also migrates those dependencies for you when you set the following two flags to true in your gradle.properties file:
> 
> ```
> android.useAndroidX=true
> android.enableJetifier=true
> ```
> In case of any problems, please contact us.

Thanks for the response. We have no issues migrating to androidx, just wanted to make sure since you mentioned mixing support library versions can lead to runtime crashes.
